OLX_CARS/urls.py
from django.contrib import admin
from django.urls import path
from api.views import viewCars

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', viewCars, name='ViewCars')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_FINDERS)

api/models.py
from django.db import models


# Create your models here.
class OlxCarData(models.Model):
    brand = models.TextField(db_column='Brand', blank=True, null=True)  # Field name made lowercase.
    condition = models.TextField(db_column='Condition', blank=True, null=True)  # Field name made lowercase.
    fuel = models.TextField(db_column='Fuel', blank=True, null=True)  # Field name made lowercase.
    kms_driven = models.BigIntegerField(db_column='KMs Driven', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    model = models.TextField(db_column='Model', blank=True, null=True)  # Field name made lowercase.
    price = models.BigIntegerField(db_column='Price', blank=True, null=True)  # Field name made lowercase.
    registered_city = models.TextField(db_column='Registered City', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    transaction_type = models.TextField(db_column='Transaction Type', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    year = models.IntegerField(db_column='Year', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'olx_car_data'

api/views.py
from django.shortcuts import render, get_object_or_404
from api.models import OlxCarData
from django import forms


class ContactForm(forms.Form):
    price = forms.IntegerField(required=False)


# Create your views here.
def viewCars(request):
    if request.method == "POST":
        if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                form = ContactForm(request.POST)
                if form.is_valid():
                    query = form.cleaned_data
                    obj = OlxCarData.objects.filter(
                        price__lte=(query['price'] + 400000),
                        price__gte=(query['price'] - 400000)
                    )[1:100]  # Get Cars between given price with 4 LAC Difference. Sliced resultant rows to 100 only
                    context = {
                        'object': obj
                    }
                    return render(request, "index.html", context)

    else:
        obj = OlxCarData.objects.all().order_by('-id')[
              1:100]  # Get all rows and sliced from 1 to 100 to show only 100 rows
        context = {
            'object': obj
        }
        return render(request, "index.html", context)

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Table</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}"/>
</head>
<body>

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <label for="id_price">Filter Cars with Price</label>
        <input type="number" id="id_price" name="price" style="">
        <button type="submit">Find</button>
    </form>
{% endblock %}

<h4>100 Cars Data</h4>

<div class="limiter">
    <div class="container-table100">
        <div class="wrap-table100">
            <div class="table100 ver1 m-b-110">
                <div class="table100-head">
                    <table>
                        <thead>
                        <tr>
                            <th style="width: 15%">Brand</th>
                            <th style="width: 13%">Condition</th>
                            <th style="width: 10%">Fuel</th>
                            <th style="width: 10%">KMs Driven</th>
                            <th style="width: 13%">Model</th>
                            <th style="width: 10%">Price</th>
                            <th style="width: 12%">Registered City</th>
                            <th style="width: 12%">Transaction Type</th>
                            <th style="width: 5%">Year</th>
                        </tr>
                        </thead>
                    </table>
                </div>
                <div class="table100-body js-pscroll" style="padding-top:20px">
                    <table>
                        <tbody>
                        {% for obj in object %}
                            <tr>
                                <td style="width: 15%">{{ obj.brand }}</td>
                                <td style="width: 13%">{{ obj.condition }}</td>
                                <td style="width: 10%">{{ obj.fuel }}</td>
                                <td style="width: 10%">{{ obj.kms_driven }}</td>
                                <td style="width: 13%">{{ obj.model }}</td>
                                <td style="width: 11%">{{ obj.price }}</td>
                                <td style="width: 12%">{{ obj.registered_city }}</td>
                                <td style="width: 12%">{{ obj.transaction_type }}</td>
                                <td style="width: 5%">{{ obj.year }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('.js-pscroll').each(function () {
        var ps = new PerfectScrollbar(this);
        $(window).on('resize', function () {
            ps.update();
        })
    });


</script>
</body>
</html>